### ISSUE TITLE
Cancel button on prompt about unsaved changes does not cancel

### ISSUE THREAD

**Issue by ahiijny** [facelessuser/RawLineEdit#13]
I have Sublime Text Build 3126.

If I run `Raw Line Edit: Toggle` on a file with unsaved changes, a prompt appears:

![image](https://user-images.githubusercontent.com/5766317/31580122-d6148536-b114-11e7-995d-f93666cdfa34.png)

If I press "cancel", it reloads the file anyway to show the line endings, which discards the unsaved changes. I would expect "cancel" to cancel the toggle command and preserve the unsaved changes.

(Also, "discared" typo)

**Comment by facelessuser** [comment]
I look to reproduce the issue. If I can I'll get a fix in right away. That's not a nice bug.

**Comment by facelessuser** [comment]
So I misunderstood the issue when I first skimmed this.

If you read the dialog, it says if you choose not to save, the changes will be discarded and then the file from disk will be parsed.  The dialog is telling you what it is doing, so it shouldn't be a surprise.

With that said, I can maybe use `yes_no_cancel_dialog` instead of `yes_cancel_dialog`.  The former didn't exist when I originally wrote this.

**Comment by ahiijny** [comment]
I tried out the changes. This new 'cancel' behaviour feels more intuitive. Thanks.

**Comment by facelessuser** [comment]
Cool.  It will be probably a day or so until I can release it.
