### ISSUE TITLE
Unintuitive UI can lead to data loss

### ISSUE THREAD

**Issue by wjakobw** [facelessuser/RawLineEdit#16]
To reproduce:
Create new file in ST.
Write something.
Save the file on disk.
Make changes to the file, but don't save yet.
CTRL + SHIFT + P, choose Raw Line Edit: Toggle.
This window pops up: 

![discard_rawlineedit](https://user-images.githubusercontent.com/25064368/51324174-eead5e80-1a61-11e9-921d-e308e91e4f1a.png)

If I hit save, it saves the file and the previously saved version is gone. Edit -> Undo doesn't restore it. If I hit cancel (or the X in the corner), it loads the saved version from disk and my recent changes are gone. I suggest one of these (assuming the package needs to load from disk):
* If there are unsaved changes, just show an info message "The file has unsaved changes. Save the file before toggling Raw Line Edit."
* Have three options: Save, Discard Changes and Cancel. Cancel should just stop the action.
* At the very least rename the cancel button to something else since it doesn't behave like a normal canceling operation.

Workaround: it is possible to ignore the popup, go back to ST and save a copy, then click something in the dialog.

(The popup has a typo in "discarded".)

Windows 10, RawLineEdit v1.2.0 (latest), Sublime Text 3.1.1 Build 3176 (latest).

**Comment by facelessuser** [comment]
This is a fair argument. It should be noted that when this was originally implemented, there was no way to show dialog with 3 options.  Since then, it is possible as one of the dialogs was actually updated to use 3 options: https://github.com/facelessuser/RawLineEdit/blob/master/raw_line_edit.py#L243.

So yeah, I am okay with this dialog also being updated.
