### ISSUE TITLE
Can't see any line endings after installation

### ISSUE THREAD

**Issue by sameernyaupane** [facelessuser/RawLineEdit#6]
Hi, thanks a lot for the plugin.

I don't seem to see any line endings visually after the installation. I'm using latest ST3.

Is here something I'm missing?

Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/7300364/13769449/e0bc931e-eaa7-11e5-804f-13b7b2b85e3f.png)

Regards

**Comment by facelessuser** [comment]
Most likely this is due to an incorrect assumption of what `RawLineEdit` does.  If you take a look at [usage in the documentation](http://facelessuser.github.io/RawLineEdit/usage/#general-usage), you will see that raw line mode is an on demand mode that can be entered by invoking a specific command.

Sublime Text normalizes all line endings, so when you open a file, regardless of its possible mixed line ending state, Sublime will guess the line ending and covert all line endings to that type.  When you enter a raw line mode (via RawLineEdit), a special view is opened allowing you to see the actual raw line endings on disk.  RawLineEdit does not allow you do normal text editing **and** view and edit line endings.  Editing and saving in a normal text edit mode will normalize line endings on save.

RawLineEdit is mainly useful for viewing line endings when troubling shooting files on systems or files used by applications where line endings matter.  Maybe you are curious why a bash script is failing.  Open the file in raw line mode, maybe you will see that a line has a carriage return messing up the script execution because bash expects Unix line endings.  In general though, you will want to rely on Sublime Text's line ending normalization as I can't think of a reason where you would want to purposely mix line endings.

Hopefully that clears up the confusion.  Just look through the documentation, that should hopefully clarify any questions you have.

**Comment by sameernyaupane** [comment]
Ahh, thanks yes I got it. I thought it should display it normally without needing to go into another mode.
Thanks for the clarification.
Cheers
